### ISSUE TITLE
Adding dependency with project merge doesn't work

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-cli#142]
Create project with `web` dependency, then run `boot add --from jpa`.

Somehow recent changes in below doesn't give results:

https://github.com/spring-projects/spring-cli/blob/07a2213c2f82c7ab560aedac10d07c1f4f94f325/src/main/java/org/springframework/cli/merger/ProjectMerger.java#L387

**Comment by fabapp2** [comment]
👀
