### ISSUE TITLE
Windows standalone startup script errors

### ISSUE THREAD

**Issue by jvalkeal** [spring-projects/spring-cli#178]
Looking between jreleaser `1.10` and `1.12`:
```
2c2
< rem Generated with JReleaser 1.10.0-SNAPSHOT at 2023-11-12T14:42:47.766560409Z
---
> rem Generated with JReleaser 1.12.0-SNAPSHOT at 2024-03-28T16:48:08.276663714Z
54a55
> set JAVA_OPTS="%JAVA_OPTS% "
59c60
< %JAVACMD% %DEFAULT_JAVA_OPTS% %JAVA_OPTS% -cp %CLASSPATH% -jar "%JARSDIRS%\spring-cli-0.7.4.jar" %CMD_LINE_ARGS%
---
> %JAVACMD% %DEFAULT_JAVA_OPTS% %JAVA_OPTS% -cp "%CLASSPATH%" -jar "%JARSDIRS%\spring-cli-0.9.0-SNAPSHOT.jar" %CMD_LINE_ARGS%
```

It's the `JAVA_OPTS` causing error:

```
Error: Could not find or load main class
Caused by: java.lang.ClassNotFoundException:
```

This doesn't effect msi installer as it's using jlink.

**Comment by jvalkeal** [comment]
Instead of overriding jreleaser template files there's a PR in jreleaser to fix it in a source. We always have an option to do local override if we get trouble waiting fix.

**Comment by aalmiray** [comment]
JReleaser `1.12.0` scheduled for release by the end of April 😅

**Comment by jvalkeal** [comment]
As we're still using jreleaser snapshots this issue got fixed from upstream. We'll move to 1.12.0 when it's out.
