### ISSUE TITLE
Unable to build project on Windows 11 OS

### ISSUE THREAD

**Issue by dfcoffin** [spring-projects/spring-cli#182]
Executing ./gradlew clean build on Windows 11 using IntellIJ IDEA 2024.1 fails to build with the following messages:
![image](https://github.com/spring-projects/spring-cli/assets/1829699/216aeccd-5c05-4f9e-8cd5-f581d8b20355)
[index.txt](https://github.com/spring-projects/spring-cli/files/15001459/index.txt) To load the error report I had to change the suffix from .HTML to .txt.

The same command builds successfully on a MacBook M1 system.

**Comment by jvalkeal** [comment]
Thanks for pointing this out. Some of these are simple failed space and line termination comparisons.

`IfExpressionTests` is actually showing a shell execution bug on windows environment. I'm probably going to split this issue to multiple ones.
